// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBos9lfAMAq9CgpExy4HUXwYMgixcmH2PQ',
    appId: '1:756004166796:web:57596fc0440d239949afa9',
    messagingSenderId: '756004166796',
    projectId: 'flutter-app-2bade',
    authDomain: 'flutter-app-2bade.firebaseapp.com',
    storageBucket: 'flutter-app-2bade.firebasestorage.app',
    measurementId: 'G-F9FY1YGXZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_DfQgAn5b8BTsJAgbeJ8XZEMW1RRNhE',
    appId: '1:756004166796:android:e5db89bcbddbf4ed49afa9',
    messagingSenderId: '756004166796',
    projectId: 'flutter-app-2bade',
    storageBucket: 'flutter-app-2bade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3FN-kptDG3gShYU_Dmwkdp6xTirNEX4',
    appId: '1:756004166796:ios:0040f37ea23cf22a49afa9',
    messagingSenderId: '756004166796',
    projectId: 'flutter-app-2bade',
    storageBucket: 'flutter-app-2bade.firebasestorage.app',
    iosBundleId: 'com.example.citatec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf3FN-kptDG3gShYU_Dmwkdp6xTirNEX4',
    appId: '1:756004166796:ios:0040f37ea23cf22a49afa9',
    messagingSenderId: '756004166796',
    projectId: 'flutter-app-2bade',
    storageBucket: 'flutter-app-2bade.firebasestorage.app',
    iosBundleId: 'com.example.citatec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBos9lfAMAq9CgpExy4HUXwYMgixcmH2PQ',
    appId: '1:756004166796:web:19a84b31734efca749afa9',
    messagingSenderId: '756004166796',
    projectId: 'flutter-app-2bade',
    authDomain: 'flutter-app-2bade.firebaseapp.com',
    storageBucket: 'flutter-app-2bade.firebasestorage.app',
    measurementId: 'G-SGCHNW1ZCB',
  );
}
