import 'package:citatec/theme/oscuro.dart';
import 'package:citatec/theme/claro.dart';
import 'pages/login_page.dart';
import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:citatec/firebase_options.dart'; // This file is generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: LoginPage(),
      theme: claroTheme,
      darkTheme: oscuroTheme,
      themeMode: ThemeMode.system, // Opcional: permite cambiar según el sistema
    );
  }
}
